# Use an official Python runtime as a parent image
FROM python:3.6-slim

ENV PYTHONUNBUFFERED 1

# Set the working directory to /app
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY p8_pure_beurre/ /app

# Install any needed packages specified in requirements.txt
RUN pip install --upgrade pip==18.0
RUN pip install pipenv
RUN pipenv install --system --deploy --ignore-pipfile

# Make port 80 available to the world outside this container
# EXPOSE 8000

# Define environment variable
# ENV NAME World

# Run app.py when the container launches
# CMD pipenv run python3 manage.py runserver
